name: Build Python package
on:
  push:
    branches:
      - main

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install build
      - name: Build source distribution
        run: |
          python -m build --sdist
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
  build-linux-wheels:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["311", "312"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install cibuildwheel
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Build wheels
        env:
          CIBW_BUILD: cp${{ matrix.python }}-manylinux_x86_64
          CIBW_ARCHS: all
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_ALL_LINUX: yum install -y curl zip unzip tar; pip install ninja
          CIBW_ENVIRONMENT: VCPKG_FORCE_SYSTEM_BINARIES=1 DEBUG_VCPKG_INSTALL=1
          CIBW_ENVIRONMENT_PASS_LINUX: VCPKG_FORCE_SYSTEM_BINARIES DEBUG_VCPKG_INSTALL GITHUB_ACTIONS ACTIONS_CACHE_URL ACTIONS_RUNTIME_TOKEN
          CIBW_BUILD_VERBOSITY: 1
        run: |
          python -m cibuildwheel --output-dir dist
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-cp${{ matrix.python }}-manylinux_x86_64
          path: dist/*.whl
